In [5]:
%%capture

import torch
from torch import nn
import import_ipynb
from bpe_tokenizer import create_dataloader, raw_text

In [6]:
input_ids = torch.tensor([2, 3, 5, 1])
vocab_size = 6
output_dim = 3

In [7]:
torch.manual_seed(123)
embedding_layer = nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [8]:
print(embedding_layer(torch.tensor([3])))
print(embedding_layer(input_ids))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)
tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


In [9]:
vocab_size = 50257
output_dim = 256
token_embedding_layer = nn.Embedding(vocab_size, output_dim)

In [14]:
max_length = 4
dataloader = create_dataloader(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=True
)
data_iter = iter(dataloader)
inputs, outputs = next(data_iter)
print(f"Token IDs:\n {inputs}\n")
print(f"Input shape:\n {inputs.shape}\n")

Token IDs:
 tensor([[  465,  1182,   284,   804],
        [  340,   284,   502,   351],
        [  510,   465, 12036,    13],
        [ 3465,   644,  1245,   262],
        [ 6164,    25,   366, 16773],
        [   11,   262,  2756,   286],
        [  284,   366, 26282,   683],
        [ 6637,   286,   262, 45172]])

Input shape:
 torch.Size([8, 4])



In [15]:
token_embedding = token_embedding_layer(inputs)
token_embedding.shape

torch.Size([8, 4, 256])

In [ ]:
context_length = max_length
pos_embedding_layer = nn.Embedding(context_length, output_dim)
pos_embedding = pos_embedding_layer()